import 'bootstrap-icons/font/bootstrap-icons.css';
import 'bootstrap/dist/css/bootstrap.css';
import 'glightbox/dist/css/glightbox.css';

// Importations des components
import TopBar from './components/TopBar';
import Header from './components/Header';
import BackToTopBtn from './components/BackToTopBtn';

import type { Metadata } from "next";
import { Playfair_Display } from 'next/font/google';
import "./globals.css";


const playfair = Playfair_Display({
  subsets: ['latin'],
  display: "swap",
  variable: "--font-playfair-display",
  weight: ['400', '500', '600', '700', '800', '900']
});

export const metadata: Metadata = {
  title: "Cabinet AEG",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  return (
    <html lang="en">
      <head>
        {/* <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
          crossOrigin="anonymous"
        /> */}
      </head>
      <body className={playfair.className}>
        <TopBar />
        <Header />
        {children}
        <BackToTopBtn />
        {/* <Script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
          crossOrigin="anonymous"
          strategy="beforeInteractive"
        /> */}
      </body>
    </html>
  );
}
